# Generated by Django 3.2.5 on 2021-08-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.TextField(default='SOME STRING', max_length=3)),
                ('period1', models.DateTimeField(max_length=10)),
                ('period2', models.DateTimeField(max_length=10)),
            ],
        ),
    ]
